import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { configClient } from "../config";
import AppProvider from "@/components/app-provider";
const roboto = Roboto({ subsets: ["vietnamese"] });

console.log(configClient);

export const metadata: Metadata = {
  title: "Trang web số 1 việt nam",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  const locale = await getLocale();
  return (
    <html lang={locale}>
      <body className={`${roboto.className}`}>
        <AppProvider>
          <NextIntlClientProvider>{children}</NextIntlClientProvider>
        </AppProvider>
      </body>
    </html>
  );
}
